### PR TITLE
Idea: use `ruff` as a replacement for `flake8` + `isort` ?

### PR DESCRIPTION
**Pull request by Tom-Willemsen**
Test for adding `ruff` as a replacement for `flake8` + `isort`.

Main advantage is speed (approx 100x faster):

```
$ time isort --check .

real	0m0.420s
user	0m0.349s
sys	0m0.040s

$ time flake8 src/

real	0m0.859s
user	0m2.157s
sys	0m0.154s

$ time ruff .

real	0m0.011s
user	0m0.006s
sys	0m0.006s
```

One code change is required due to a difference in opinion between ruff and `isort` about constructs like:

```python
from somewhere import thing1
from somewhere import thing2 as aliased_name
from somewhere import thing3
```
which ruff prefers formatted as:
```python
from somewhere import thing1, thing3
from somewhere import thing2 as aliased_name
```

Other than that it is a 1:1 replacement in terms of linting rules.

This seems to be the direction a lot of modern python projects are moving in, and a better dev experience with `pre-commit` etc is always nice.

### CODE REVIEW

**Review by DominicOram — COMMENTED** [review]
This worked for me but required a bit of faffing to get vscode happy. Had to change `Python: Select Linter` to None and install the ruff extension. @dperl-dls, do you have strong opinions on this? One issue is that we're now using a different formatter to `dodal`.

**Comment by Tom-Willemsen** [comment]
> One issue is that we're now using a different formatter to dodal.

I agree if we decide to use this we should also do an equivalent migration on `dodal` - I only opened the one PR initially in order to get opinions and not waste too much time if we decide we don't like this.

**Comment by DominicOram** [comment]
> > One issue is that we're now using a different formatter to dodal.
> 
> I agree if we decide to use this we should also do an equivalent migration on `dodal` - I only opened the one PR initially in order to get opinions and not waste too much time if we decide we don't like this.

In which case we should probably ask @callumforrester

**Comment by dperl-dls** [comment]
I don't have a very strong opinion on this but I have noticed some slowdown with flake8 so I am mildly in favour

**Comment by callumforrester** [comment]
@coretl, weren't you looking at migrating the skeleton to ruff at some point?

**Comment by coretl** [comment]
we are planning to, but haven't had time yet: https://github.com/DiamondLightSource/python3-pip-skeleton/issues/142

**Comment by DominicOram** [comment]
Is a better way to do this to change the skeleton then merge it in here and `dodal` then?

**Comment by coretl** [comment]
@Tom-Willemsen just volunteered to do this and I said yes please...

**Comment by Tom-Willemsen** [comment]
See https://github.com/DiamondLightSource/python3-pip-skeleton/pull/147

**Comment by Tom-Willemsen** [comment]
This PR is now a cherry-pick/merge of https://github.com/DiamondLightSource/python3-pip-skeleton/pull/147 .

**Review by DominicOram — APPROVED** [review]
Looks good to me, thanks. Can we merge it into dodal too please?

**Pull request merged**
