### PR TITLE
More renaming some files to Hyperion

### LINKED ISSUE #873: Files still named Artemis
There are a couple of files we forgot to rename:
* `deploy_artemis.py`
* `python-artemis.code-workspace`

Fix these and confirm no others exist

### PR DESCRIPTION
**Pull request by Gon-reina**
Fixes #873
Renamed 3 files that were still named artemis as mentioned by @DominicOram

### CODE REVIEW

**Comment by DominicOram** [comment]
This is good, thank you! We need to correspondingly change the wiki. e.g. https://github.com/DiamondLightSource/hyperion/wiki/Getting-Started-as-a-Developer. I can do that

**Review by DominicOram — CHANGES_REQUESTED** [review]
On second thoughts, I think we can get away with just calling them both just `hyperion.code-workspace` i.e. drop the `python` bit

**Review by Gon-reina — COMMENTED** [review]
Done as requested, dropped the python- in .vscode/hyperion.code-workspace

**Review by DominicOram — CHANGES_REQUESTED** [review]
Sorry to be pedantic, can we drop the `python` part of the `dodal-nexgen` file too?

**Review by Gon-reina — COMMENTED** [review]
No worries, should be done now!

**Review by DominicOram — APPROVED** [review]
Great, thanks. I've changed the name in the wiki and will merge this. What brought you to the repo @Gon-reina? If you're interested in learning some context of what we're doing see [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwip9b3_-JWBAxWDX0EAHSWwC2MQFnoECBoQAQ&url=https%3A%2F%2Findico.psi.ch%2Fevent%2F12738%2Fcontributions%2F38933%2Fattachments%2F22725%2F40071%2FArtemis%2520Poster%2520NOBUGS%25202022.pdf&usg=AOvVaw1tIE27JwCrk4xp4dOXDSp0&opi=89978449)

**Comment by Gon-reina** [comment]
Well I've looking for interesting python based repositories to contribute to and I am a physicist by training, thought this was pretty interesting. I have experience as a programmer too I just haven't worked on open source projects and I thought it would look good on my cv/profile. I just read through your poster and sounds very cool, I have worked with flask before and have dabbled in data analysis pipelines with MATLAB. I am more than happy to help with more stuff as well, maybe some actual coding, will read through the issues!

**Comment by DominicOram** [comment]
Great! I'm afraid I won't have time in the foreseeable future to talk you through any of the issues and a lot of them probably require quite a bit of background but if you find something you think you might have enough background to do then feel free to comment on it to say you're going to give it a go and we'll try and answer any questions you have.

**Pull request merged**
