### PR TITLE
Update to ophyd_async shutter

### PR DESCRIPTION
**Pull request by DominicOram**
Link to dodal PR (if required): https://github.com/DiamondLightSource/dodal/pull/480

### To test:
1. Confirm tests still pass

### CODE REVIEW

**Comment by stan-dot** [comment]
@DominicOram when you say merge at the same time, you mean into master one day  or one PR into another?

**Comment by DominicOram** [comment]
> @DominicOram when you say merge at the same time, you mean into master one day or one PR into another?

Both into `main` on their respective repos at around the same time

**Comment by stan-dot** [comment]
not sure what to do about the CI error: 
> 
0s
Run item_id="$( gh api graphql -f query='
  item_id="$( gh api graphql -f query='
    mutation($project:ID!, $pr:ID!) {
      addProjectV2ItemById(input: {projectId: $project, contentId: $pr}) {
        item {
          id
        }
      }
    }' -f project=$PROJECT_ID -f pr=$ISSUE_ID --jq '.data.addProjectV2ItemById.item.id')"
  
    echo 'ITEM_ID='$item_id >> $GITHUB_ENV
  shell: /usr/bin/bash -e {0}
  env:
    PROJECT_ID: "PVT_kwDOABLS0s4AHJ2Y"
    STATUS_FIELD_ID: "PVTSSF_lADOABLS0s4AHJ2YzgEH3Zs"
    NEW_OPTION_ID: "e133e26f"
    GITHUB_TOKEN: ***
    ISSUE_ID: null
gh: Could not resolve to a node with the global id of 'null'
Error: Process completed with exit code 1.

**Comment by DominicOram** [comment]
> not sure what to do about the CI error:

You can ignore them. They're for moving issues around the hyperion project board but this isn't being tracked on the hyperion project board

**Comment by DominicOram** [comment]
Closing in favour of https://github.com/DiamondLightSource/hyperion/pull/1419

**Pull request closed without merging**
