### PR TITLE
Use the tmpdir fixture for tests that create files

### LINKED ISSUE #994: Use pytest's tmpdir fixture for tests which require creating files
To me this feels nicer than having to manually create and remove test files each time

### PR DESCRIPTION
**Pull request by olliesilvester**
Fixes #994

### To test:
1. Run tests
2. Check if change is useful/makes sense

### CODE REVIEW

**Review by dperl-dls — CHANGES_REQUESTED** [review]
I didn't know about this fixture, this does seem nice!

It doesn't seem like your `temp_directory fixture` is doing anything different to the builtin `tmpdir`? so I think we can just use that. Also in that case you can delete the `.../test_data/scratch` directory and `.gitignore` entries

**Comment by olliesilvester** [comment]
thanks, didnt see it was in the gitignore

**Review by dperl-dls — APPROVED** [review]
Looks good, thanks!

**Comment by DominicOram** [comment]
Nit: Can you tidy up the PR name to make more sense to a user please?

**Pull request merged**
